workspace:
  base: /go
  path: src/github.com/kubeciio/kubectl

pipeline:
  dep:
    image: metalmatze/dep:0.4.1
    pull: true
    commands:
      - dep ensure -v -vendor-only

  test:
    group: go
    image: golang:1.10-alpine
    pull: true
    commands:
      - go test -v ./...

  build:
    group: go
    image: golang:1.10-alpine
    pull: true
    commands:
      - CGO_ENABLED=0 go build -o kubeciio-kubectl ./cmd/kubeciio-kubectl

  docker:
    image: plugins/docker:17
    pull: true
    repo: kubeciio/kubectl
    secrets: [ docker_username, docker_password ]
    tag: [ 0.2, 0.2.1, latest ]
    when:
      event: tag
