workspace:
  base: /go
  path: src/github.com/kubeciio/kubectl

pipeline:
  dep:
    image: metalmatze/dep:0.4.1
    commands:
      - dep ensure -v -vendor-only

  test:
    group: go
    image: golang:alpine
    commands:
      - go test -v ./...

  build:
    group: go
    image: golang:alpine
    commands:
      - CGO_ENABLED=0 go build -o kubeciio-kubectl ./cmd/kubeciio-kubectl

  docker:
    image: plugins/docker
    repo: kubeciio/kubectl
    secrets: [ docker_username, docker_password ]
